
package com.atguigu.webservice.zsdf020;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_ZSDF_020_SenderService", targetNamespace = "http://www.lingong..com/ZSDF_020", wsdlLocation = "file:/C:/Users/xiaoxiang/AppData/Local/Temp/tempdir1405063504740251035.tmp/wsdl_1.wsdl")
public class SIZSDF020SenderService
    extends Service
{

    private final static URL SIZSDF020SENDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIZSDF020SENDERSERVICE_EXCEPTION;
    private final static QName SIZSDF020SENDERSERVICE_QNAME = new QName("http://www.lingong..com/ZSDF_020", "SI_ZSDF_020_SenderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/xiaoxiang/AppData/Local/Temp/tempdir1405063504740251035.tmp/wsdl_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIZSDF020SENDERSERVICE_WSDL_LOCATION = url;
        SIZSDF020SENDERSERVICE_EXCEPTION = e;
    }

    public SIZSDF020SenderService() {
        super(__getWsdlLocation(), SIZSDF020SENDERSERVICE_QNAME);
    }

    public SIZSDF020SenderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIZSDF020SENDERSERVICE_QNAME, features);
    }

    public SIZSDF020SenderService(URL wsdlLocation) {
        super(wsdlLocation, SIZSDF020SENDERSERVICE_QNAME);
    }

    public SIZSDF020SenderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIZSDF020SENDERSERVICE_QNAME, features);
    }

    public SIZSDF020SenderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIZSDF020SenderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIZSDF020Sender
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIZSDF020Sender getHTTPPort() {
        return super.getPort(new QName("http://www.lingong..com/ZSDF_020", "HTTP_Port"), SIZSDF020Sender.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZSDF020Sender
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIZSDF020Sender getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.lingong..com/ZSDF_020", "HTTP_Port"), SIZSDF020Sender.class, features);
    }

    /**
     * 
     * @return
     *     returns SIZSDF020Sender
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIZSDF020Sender getHTTPSPort() {
        return super.getPort(new QName("http://www.lingong..com/ZSDF_020", "HTTPS_Port"), SIZSDF020Sender.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIZSDF020Sender
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIZSDF020Sender getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.lingong..com/ZSDF_020", "HTTPS_Port"), SIZSDF020Sender.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIZSDF020SENDERSERVICE_EXCEPTION!= null) {
            throw SIZSDF020SENDERSERVICE_EXCEPTION;
        }
        return SIZSDF020SENDERSERVICE_WSDL_LOCATION;
    }

}
