
package com.atguigu.webservice.zsdf020;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_ZSDF_020_Sender", targetNamespace = "http://www.lingong..com/ZSDF_020")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIZSDF020Sender {


    /**
     * 
     * @param mtZSDF020Req
     * @return
     *     returns dms.core.s4.ws.DTZSDF020Res
     */
    @WebMethod(operationName = "SI_ZSDF_020_Sender", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_ZSDF_020_Res", targetNamespace = "http://www.lingong..com/ZSDF_020", partName = "MT_ZSDF_020_Res")
    public DTZSDF020Res siZSDF020Sender(
        @WebParam(name = "MT_ZSDF_020_Req", targetNamespace = "http://www.lingong..com/ZSDF_020", partName = "MT_ZSDF_020_Req")
        DTZSDF020Req mtZSDF020Req);

}
